modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="summoningscroll"
version="1.0.0"
displayName="Summoning Scroll"
authors="LightMildTea"
description='''
Added a Scroll to summon an Entity to the game
'''

[[mixins]]
config="summoningscroll.mixins.json"

[[dependencies.summoningscroll]]
modId="neoforge"
type="required"
versionRange="[21.1.226,)"
ordering="NONE"
side="BOTH"

[[dependencies.summoningscroll]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.summoningscroll]]
modId="jei"
type="optional"
versionRange="[19.21.0.247,)"
ordering="NONE"
side="CLIENT"

